-- CREATE DATA BASE 
CREATE DATABASE INS ;
USE INS;
-- CREATE TABLE 
CREATE TABLE USER (
	ID LONG ,
    EMAIL VARCHAR(255),
    FIRSTNAME nvarchar(50),
    LASTNAME NVARCHAR(50),
    ADDRESS VARCHAR(255),
    LOCATION VARCHAR(50),
    ROLE VARCHAR(20)
);
-- SELECT * FROM USER
SELECT * FROM USER ;
-- TEST INSERT INTO 
INSERT INTO USER VALUES(1,'nhutanhtran806@gmail.com','Anh','Tran','HCMC','VIETNAM');
-- ADD ROLE COL
ALTER TABLE USER 
ADD ROLE VARCHAR(20);
-- SET ROLE 
UPDATE USER
SET ROLE = "Admin"
WHERE ID = 1 ;

-- CREATE POST TABLE 
CREATE TABLE POST (
PostID LONG ,
Description NVARCHAR(255),
TimePost INT ,
REACT INT ,
MediaId LONG ,
CommentId LONG
);
-- CREATE MEDIA TABLE 
CREATE TABLE MEDIA (
MediaID INT   AUTO_INCREMENT PRIMARY KEY,
URL VARCHAR(255),
NAME NVARCHAR(255),
PostID LONG 
);
-- CREATE COMMENT TABLE 
CREATE TABLE COMMENT (
CommentID INT AUTO_INCREMENT PRIMARY KEY ,
Content NVARCHAR(255),
TimeComment INT ,
REACT INT ,
USERID INT 
);

