-- CREATE DATA BASE 
CREATE DATABASE INS ;
USE INS;
-- CREATE TABLE 
CREATE TABLE USER (
	ID LONG ,
    EMAIL VARCHAR(255),
    FIRSTNAME nvarchar(50),
    LASTNAME NVARCHAR(50),
    ADDRESS VARCHAR(255),
    LOCATION VARCHAR(50),
    ROLE VARCHAR(20)
);
-- SELECT * FROM USER
SELECT * FROM USER ;
-- TEST INSERT INTO 
INSERT INTO USER VALUES(1,'nhutanhtran806@gmail.com','Anh','Tran','HCMC','VIETNAM');
-- ADD ROLE COL
ALTER TABLE USER 
ADD ROLE VARCHAR(20);
-- SET ROLE 
UPDATE USER
SET ROLE = "Admin"
WHERE ID = 1 ;


